[pytest]
pythonpath = src
filterwarnings =
    ignore::UserWarning:plyer
    ignore:.*multi-threaded.*fork.*:DeprecationWarning:multiprocessing
    ignore::UserWarning:_distutils_hack
    ignore:.*crypt.*:DeprecationWarning:codext
