#!/usr/bin/env python
from tinyscript import *
from tinyscript.template import new

from tinyscript.__info__ import __author__, __copyright__


__version__ = "1.0"
__examples__ = ["script", "tool",
                "script pybots.HTTPBot", "tool pybots.JSONBot"]
__doc__ = """
This tool allows to quickly create a new Tinyscript script/tool from a template.
"""


if __name__ == '__main__':
    parser.add_argument("target", default=["script"], nargs="*",
                        help="target to be created (default: script)")
    initialize(globals())
    new(args.target)
